# Generated by Django 6.0.4 on 2026-04-15 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Hypercar', 'Hypercar')], max_length=20)),
                ('price_inr', models.PositiveBigIntegerField(help_text='Price in INR')),
                ('description', models.TextField()),
                ('range_km', models.PositiveIntegerField(help_text='Range in kilometers')),
                ('top_speed', models.PositiveIntegerField(help_text='Top speed in km/h')),
                ('acceleration_0_100', models.FloatField(help_text='0-100 km/h in seconds')),
                ('image_url', models.URLField()),
                ('is_flagship', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TestDrive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('preferred_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.car')),
            ],
        ),
    ]
