# Generated by Django 6.0.4 on 2026-04-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='type',
            field=models.CharField(choices=[('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Hypercar', 'Hypercar'), ('Hatchback', 'Hatchback')], max_length=20),
        ),
    ]
